name: Go

on: [push, pull_request]

env:
  VERSION: 1.13.x
  GO111MODULE: on
  IMPORT_PATH: github.com/brancz/kube-rbac-proxy
  QUAY_PATH: quay.io/brancz/kube-rbac-proxy

jobs:
  create-cluster: # OK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create cluster
      run: |
        curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
        kind create cluster --config test/e2e/kind-config/kind-config.yaml
      continue-on-error: false
    - name: Create container & run tests
      run: |
        VERSION=local make container
        kind load docker-image ${QUAY_PATH}:local
        make test-e2e
    - name: Build Push
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v1
      with:
        username: ${QUAY_USERNAME}
        password: ${QUAY_PASSWORD}
        registry: ${QUAY_PATH}
        repository: ${IMPORT_PATH}
        tags: ${GITHUB_REF}
