name: Go

on: [push, pull_request]

env:
  VERSION: 1.13.x
  GO111MODULE: on
  IMPORT_PATH: github.com/brancz/kube-rbac-proxy

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
        kind create cluster --config ${IMPORT_PATH}/test/e2e/kind-config/kind-config.yaml
  make-container:
    name: Make container and E2E test
    needs: create-cluster
    runs-on: ubuntu-latest
    steps:
    - run: |
        VERSION=local make container
        kind load docker-image quay.io/brancz/kube-rbac-proxy:local
        make test-e2e
  build-push:
    name: build-push
    needs: make-container
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${QUAY_USERNAME}
        password: ${QUAY_PASSWORD}
        registry: quay.io/brancz/kube-rbac-proxy
        repository: github.com/brancz/kube-rbac-proxy
        tags: v1
