name: Go

on: [push, pull_request]

env:
  VERSION: 1.13.x
  GO111MODULE: on
  IMPORT_PATH: github.com/markkuleppala/kube-rbac-proxy
  QUAY_PATH: quay.io/brancz/kube-rbac-proxy
  QUAY_REPOSITORY: markku/kube-rbac-proxy

jobs:
  create-cluster: # OK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    #- name: Create cluster
    #  run: |
    #    curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
   #    kind create cluster --config test/e2e/kind-config/kind-config.yaml
    #  continue-on-error: false
    - name: Create container & run tests
      run: |
        VERSION=local make container
      #  kind load docker-image ${QUAY_PATH}:local
      #  make test-e2e
  #login-push:
  #  if: ${{ github.event_name != 'pull_request' }}
  #  runs-on: ubuntu-latest
  #  steps:
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Build and push
      run: |
        TAG="$(git rev-parse --abbrev-ref HEAD | tr / -)-$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)"
        ID="$(docker images ${QUAY_PATH}:local --format "{{.ID}}")"
        echo $TAG $ID
        docker tag $ID ${QUAY_REPOSITORY}:$TAG
        docker push quay.io/${QUAY_REPOSITORY}:$TAG
    # TAG="$(docker images ${QUAY_PATH}:local --format "{{.ID}}")"

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # - name: Push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./
    #     file: ./Dockerfile
    #     push: true
    #     tags: markku/kube-rbac-proxy:local